server:
  port: 9003
  error:
    whitelabel:
      enabled: true
    path: /projectassistant-error
  tomcat:
    max-threads: 100
    max-swallow-size: 1MB
    max-http-post-size: 1MB
    accesslog:
      enabled: true
      directory: accesslog
      file-date-format: yyyy-MM-dd
      prefix: accesslog
      suffix: .log
  connection-timeout: 5s
  max-http-header-size: 10KB
#  ssl:
#    enabled: true
#    protocol: TLS
#    key-store: keystore-path
#    key-store-password: my_password
#    key-alias: projectassistant

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @profile@
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      host: @mongo.host@
      database: @mongo.database.name@
#      username: @mongo.root.username@
#      password: @mongo.root.password@

logging:
  level:
    root: warn
    org.apache.activemq: debug
    org.springframework.jms: debug
    org.springframework: info

activemq:
  queue:
    name: @activemq.queue.name@
  broker:
    url: @activemq.broker.url@
  producer:
    name: @activemq.producer.name@
    password: @activemq.producer.password@
