server:
  port: 9001
  error:
    whitelabel:
      enabled: true
    path: /projectassistant-error
  tomcat:
    max-threads: 100
    max-swallow-size: 1MB
    max-http-post-size: 1MB
    accesslog:
      enabled: true
      directory: accesslog
      file-date-format: yyyy-MM-dd
      prefix: accesslog
      suffix: .log
  connection-timeout: 5s
  max-http-header-size: 10KB
#  ssl:
#    enabled: true
#    protocol: TLS
#    key-store: keystore-path
#    key-store-password: my_password
#    key-alias: projectassistant

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: test
  devtools:
    restart:
      enabled: true
  activemq:
    broker-url: tcp://127.0.0.1:61616
    packages:
      trusted: org.springframework.remoting.support,java.lang,hu.bme.szakdolgozat

logging:
  level:
    root: warn
    org.apache.activemq: debug
    org.springframework.jms: debug
    org.springframework: info
