server:
  port: 9003
  error:
    whitelabel:
      enabled: true
    path: /projectassistant-error
  tomcat:
    max-threads: 100
    max-swallow-size: 1MB
    max-http-post-size: 1MB
    accesslog:
      enabled: true
      directory: accesslog
      file-date-format: yyyy-MM-dd
      prefix: accesslog
      suffix: .log
  connection-timeout: 5s
  max-http-header-size: 10KB

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @profile@
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      host: @mongo.host@
      database: @mongo.database.name@

logging:
  level:
    root: warn
    org.apache.activemq: debug
    org.springframework.jms: debug
    org.springframework: info

activemq:
  queue:
    name: @activemq.queue.name@
  broker:
    url: @activemq.broker.url@
  producer:
    name: @activemq.producer.name@
    password: @activemq.producer.password@


app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: @tokenExpirationMsec@
  oauth2:
    authorizedRedirectUri:
      - http://localhost:9004/oauth2/redirect
