version: "3.2"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
      - ./certs:/certs
    networks:
      - dockernet
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
      - "80:80"
      - "443:443"

networks:
  dockernet:
    external: true

