version: "3.2"

services:

  activemq:
    image: rmohr/activemq
    hostname: activeMQ
    container_name: activeMQ
    networks:
      message:
        aliases:
          - activemq
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    environment:
      - ACTIVEMQ_CONFIG_DEFAULTACCOUNT="false"
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin123
      - ACTIVEMQ_USERS_myproducer=myproducerpassword
      - ACTIVEMQ_GROUPS_writes=myproducer
      - ACTIVEMQ_USERS_myconsumer=myconsumerpassword
      - ACTIVEMQ_GROUPS_reads=myconsumer
      - ACTIVEMQ_CONFIG_QUEUES_projectAssistant1=projectAssistant


  messageservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: message-service
    networks:
      - message
    hostname: message-service
    volumes:
      - ./config:/app/config
    ports:
      - "9002:9002"


networks:
  message:
    external: true
