pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube Analyze') {
            withSonarQubeEnv(credentialsId: '	sonaqube-token', installationName: 'sonaqube-token') {
              sh 'mvn clean verify sonar:sonar'
        }
    }
    
}
