pipeline {
    agent any
    tools {
        maven 'MAVEN3'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'cd ProjectAssistant && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd ProjectAssistant && mvn test'
            }
            post {
                always {
                    junit testResults: '**/target/surefire-reports/*.xml', allowEmptyResults: true
                }
            }
        }
        stage('SonarQube Analyze') {
            steps {
                withSonarQubeEnv(credentialsId: 'sonaqube-token', installationName: 'sonaqube-token') {
                    sh 'cd ProjectAssistant && mvn clean verify sonar:sonar'
                }
            }
        }
    }
    post {
        failure {
            emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}"
        }
    }
}
