pipeline {
    agent any
    tools {
        maven: 'MAVEN3'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'cd ProjectAssistant && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd ProjectAssistant && mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('SonarQube Analyze') {
            steps {
                withSonarQubeEnv(credentialsId: 'sonaqube-token', installationName: 'sonaqube-token') {
                    sh 'cd ProjectAssistant && mvn clean verify sonar:sonar'
                }
            }
        }
    }
    
}
