server:
  port: 9002
  connection-timeout: 5s
  tomcat:
    max-threads: 100
    max-swallow-size: 1MB
    max-http-post-size: 1MB
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/authentication.p12
    key-store-password: authentication
    key-alias: authentication

spring:
  data:
    mongodb:
      host: @ip.address@
      port: 27020
      database: @authentication.database.name@

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 2318941121751144
            clientSecret: c115893acdd55be9834176570572a767
            redirect-uri: @protocol@://@ip.address@@pre.tag@/oauth2/callback/{registrationId}
            authorize-uri: @protocol@://@ip.address@@pre.tag@/oauth2/authorize/facebook
            scope:
              - email
              - public_profile
          google:
            clientId: 30072480563-b2ej91p8rhsr3mjrtgbhogm73u3rlrmb.apps.googleusercontent.com
            clientSecret: mlcdz29Cu43WTj_RcZfZXCWl
            redirect-uri: @protocol@://@ip.address@@pre.tag@/oauth2/callback/{registrationId}
            authorize-uri: @protocol@://@ip.address@@pre.tag@/oauth2/authorize/google
            scope:
              - email
              - profile
              - openid
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenUri: https://www.googleapis.com/oauth2/v4/token
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: @tokenExpirationMsec@
