server:
  port: 9002

activemq:
  queue:
    name: @activemq.queue.name@
  broker:
    url: @activemq.broker.url@
  consumer:
    name: @activemq.consumer.name@
    password: @activemq.consumer.password@
